imports:
    - { resource: parameters.yml }

framework:
    secret:
        key: "abc"
assetic:
    debug: '%kernel.debug%'
    use_controller: false
    bundles:
        - MetTradersLayoutBundle
        - MetTradersPageBundle
        - MetTradersAdminBundle
        - ModernBusinessThemeBundle
    filters:
        cssrewrite: null
doctrine:
    dbal:
        driver: '%database_driver%'
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true
        mappings:
            translatable: { type: annotation, alias: Gedmo, prefix: Gedmo\Translatable\Entity, dir: '%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity' }
parameters:
    assets_dir: /home/assets/MetTraders
    met_traders_email_noreply: noreply@mettraders.com
